# Generated by Django 5.2.11 on 2026-05-29 20:48

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kernelCI_app", "0019_add_commits_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildDefinitions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_timestamp",
                    models.DateTimeField(blank=True, db_column="_timestamp", null=True),
                ),
                ("origin", models.TextField()),
                ("architecture", models.TextField(blank=True, null=True)),
                ("compiler", models.TextField(blank=True, null=True)),
                ("config_name", models.TextField(blank=True, null=True)),
                ("series", models.TextField()),
                (
                    "checkout",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="kernelCI_app.checkouts",
                    ),
                ),
            ],
            options={
                "db_table": "build_definitions",
            },
        ),
        migrations.CreateModel(
            name="BuildRuns",
            fields=[
                (
                    "field_timestamp",
                    models.DateTimeField(blank=True, db_column="_timestamp", null=True),
                ),
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("origin", models.TextField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("command", models.TextField(blank=True, null=True)),
                ("input_files", models.JSONField(blank=True, null=True)),
                ("output_files", models.JSONField(blank=True, null=True)),
                ("config_url", models.TextField(blank=True, null=True)),
                ("log_url", models.TextField(blank=True, null=True)),
                (
                    "log_excerpt",
                    models.CharField(blank=True, max_length=16384, null=True),
                ),
                ("misc", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("SKIP", "Skip"),
                            ("ERROR", "Error"),
                            ("MISS", "Miss"),
                            ("DONE", "Done"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "build_definition",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="kernelCI_app.builddefinitions",
                    ),
                ),
                (
                    "checkout",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="kernelCI_app.checkouts",
                    ),
                ),
            ],
            options={
                "db_table": "build_runs",
            },
        ),
        migrations.AddField(
            model_name="incidents",
            name="build_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="kernelCI_app.buildruns",
            ),
        ),
        migrations.CreateModel(
            name="TestDefinitions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_timestamp",
                    models.DateTimeField(blank=True, db_column="_timestamp", null=True),
                ),
                ("path", models.TextField(blank=True, null=True)),
                (
                    "number_prefix",
                    models.CharField(
                        blank=True,
                        choices=[("metric", "Metric"), ("binary", "Binary")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("number_unit", models.TextField(blank=True, null=True)),
                (
                    "build_definition",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="kernelCI_app.builddefinitions",
                    ),
                ),
            ],
            options={
                "db_table": "test_definitions",
            },
        ),
        migrations.CreateModel(
            name="TestRuns",
            fields=[
                (
                    "field_timestamp",
                    models.DateTimeField(blank=True, db_column="_timestamp", null=True),
                ),
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("origin", models.TextField()),
                ("environment_comment", models.TextField(blank=True, null=True)),
                ("environment_misc", models.JSONField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("log_url", models.TextField(blank=True, null=True)),
                (
                    "log_excerpt",
                    models.CharField(blank=True, max_length=16384, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("SKIP", "Skip"),
                            ("ERROR", "Error"),
                            ("MISS", "Miss"),
                            ("DONE", "Done"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("input_files", models.JSONField(blank=True, null=True)),
                ("output_files", models.JSONField(blank=True, null=True)),
                ("misc", models.JSONField(blank=True, null=True)),
                ("number_value", models.FloatField(blank=True, null=True)),
                (
                    "environment_compatible",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "build_run",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="kernelCI_app.buildruns",
                    ),
                ),
                (
                    "test_definition",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="kernelCI_app.testdefinitions",
                    ),
                ),
            ],
            options={
                "db_table": "test_runs",
            },
        ),
        migrations.AddField(
            model_name="incidents",
            name="test_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="kernelCI_app.testruns",
            ),
        ),
        migrations.AddIndex(
            model_name="builddefinitions",
            index=models.Index(
                fields=["field_timestamp"], name="build_defs__timestamp"
            ),
        ),
        migrations.AddIndex(
            model_name="builddefinitions",
            index=models.Index(
                fields=["checkout", "series"], name="build_defs_checkout_series"
            ),
        ),
        migrations.AddIndex(
            model_name="builddefinitions",
            index=models.Index(fields=["origin"], name="build_defs_origin"),
        ),
        migrations.AddConstraint(
            model_name="builddefinitions",
            constraint=models.UniqueConstraint(
                fields=("checkout", "series"),
                name="build_definitions_checkout_series_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddIndex(
            model_name="buildruns",
            index=models.Index(
                fields=["field_timestamp"], name="build_runs__timestamp"
            ),
        ),
        migrations.AddIndex(
            model_name="buildruns",
            index=models.Index(
                fields=["build_definition"], name="build_runs_definition"
            ),
        ),
        migrations.AddIndex(
            model_name="buildruns",
            index=models.Index(fields=["checkout"], name="build_runs_checkout"),
        ),
        migrations.AddIndex(
            model_name="buildruns",
            index=models.Index(fields=["origin"], name="build_runs_origin"),
        ),
        migrations.AddIndex(
            model_name="buildruns",
            index=models.Index(fields=["start_time"], name="build_runs_start_time"),
        ),
        migrations.AddIndex(
            model_name="buildruns",
            index=models.Index(fields=["status"], name="build_runs_status"),
        ),
        migrations.AddIndex(
            model_name="testdefinitions",
            index=models.Index(fields=["field_timestamp"], name="test_defs__timestamp"),
        ),
        migrations.AddIndex(
            model_name="testdefinitions",
            index=models.Index(fields=["build_definition"], name="test_defs_build_def"),
        ),
        migrations.AddIndex(
            model_name="testdefinitions",
            index=models.Index(fields=["path"], name="test_defs_path"),
        ),
        migrations.AddConstraint(
            model_name="testdefinitions",
            constraint=models.UniqueConstraint(
                fields=("build_definition", "path", "number_prefix", "number_unit"),
                name="test_definitions_build_path_number_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddIndex(
            model_name="testruns",
            index=models.Index(fields=["field_timestamp"], name="test_runs__timestamp"),
        ),
        migrations.AddIndex(
            model_name="testruns",
            index=models.Index(fields=["test_definition"], name="test_runs_definition"),
        ),
        migrations.AddIndex(
            model_name="testruns",
            index=models.Index(fields=["build_run"], name="test_runs_build_run"),
        ),
        migrations.AddIndex(
            model_name="testruns",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["environment_compatible"], name="test_runs_compatible"
            ),
        ),
        migrations.AddIndex(
            model_name="testruns",
            index=models.Index(fields=["origin"], name="test_runs_origin"),
        ),
        migrations.AddIndex(
            model_name="testruns",
            index=models.Index(
                django.db.models.expressions.RawSQL(
                    "(environment_misc ->> 'platform')", []
                ),
                name="test_runs_platform_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="testruns",
            index=models.Index(fields=["start_time"], name="test_runs_start_time"),
        ),
        migrations.AddIndex(
            model_name="testruns",
            index=models.Index(fields=["status"], name="test_runs_status"),
        ),
    ]
