name: Deploy Dashboard from fresh-built images

permissions:
  contents: read
  actions: read
  packages: read

on:
  workflow_call:
    inputs:
      ref:
        description: Commit reference (branch, tag or sha) to deploy
        required: true
        type: string

    secrets:
      ssh_user:
      ssh_host_address:
      ssh_host_pubkey:
      ssh_private_key:

      wg_client_key:
      wg_client_vpn_ip:
      wg_host_pubkey:
      wg_host_endpoint:
      wg_vpn_subnet:

jobs:
  deploy-from-source:
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      SSH_ID: "${{ secrets.ssh_user }}@${{ secrets.ssh_host_address }}"
      COMPOSE_PROGRESS: plain
      COMPOSE_REMOVE_ORPHANS: 'true'
    steps:
      - name: Checkout staging branch # Needed for actions/workflow reuse
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
        with:
          ref: staging

      - name: Connect to Private VPN
        uses: ./.github/actions/connect-wireguard
        with:
          client_key: ${{ secrets.wg_client_key }}
          client_vpn_ip: ${{ secrets.wg_client_vpn_ip }}
          host_public_key: ${{ secrets.wg_host_pubkey }}
          host_endpoint: ${{ secrets.wg_host_endpoint }}
          vpn_subnet: ${{ secrets.wg_vpn_subnet }}

      - name: Configure SSH auth
        shell: bash
        run: |
          mkdir -p ~/.ssh/ && chmod 700 ~/.ssh/
          touch ~/.ssh/known_hosts && chmod 600 ~/.ssh/known_hosts
          echo "$SSH_HOSTKEY" > ~/.ssh/known_hosts
          echo "StrictHostKeyChecking=yes" >> ~/.ssh/config
          eval $(ssh-agent -a "$SSH_AUTH_SOCK")
          ssh-add -q - <<< "$SSH_KEY"
        env:
          SSH_HOSTKEY: ${{ secrets.ssh_host_pubkey }}
          SSH_KEY: ${{ secrets.ssh_private_key }}

      - name: Checkout repository # Actual branch being deployed
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
        with:
          ref: ${{ inputs.ref }}

      - name: Set Docker Compose project name and tag
        run: |
          # Sanitize branch name: replace invalid characters with hyphens,
          # prepend gha and trim non-alphanumeric characters from end.
          clean_ref=$(echo "gha-${{ inputs.ref }}" \
            | sed -E 's/[^a-z0-9_-]/-/g' \
            | sed -E 's/[^a-z0-9]+$//g')

          echo "COMPOSE_PROJECT_NAME=${clean_ref}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${clean_ref}" >> $GITHUB_ENV

      - name: Setup Docker
        uses: docker/setup-docker-action@6d7cfa65f60a9dda7b46e5513fa982536f3c9877 # v5.3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build images locally
        shell: bash
        run: touch .env && docker compose build

      - name: Setup remote docker
        shell: bash
        run: docker context create remote-server --docker "host=ssh://${SSH_ID}"

      - name: Copy images to remote
        shell: bash
        run: |
          docker compose config --format json \
            | jq -r '.services[] | select(.build != null) | .image' \
            | xargs docker save \
            | docker --context=remote-server load

      - name: Run services on remote
        shell: bash
        run: docker --context=remote-server compose up --wait --timeout=60 --wait-timeout=60
